server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  rabbitmq:
    host: localhost
    port: 15672
    virtual-host: /srmhost
    username: srm
    password: 123123

#阿里云短信
aliyun:
  sms:
    regin-id: cn-hangzhou
    key-id: LTAI4G5Svnb2TWBMuKnNT6jY
    key-secret: N7v6R4V3EJ1SGDZlsqtqo8QyVVMmtQ
    template-code: SMS_96695065
    sign-name: 谷粒

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  #开启Feign对Sentinel的支持
  #feign:
  sentinel:
    enabled: true
logging:
  level:
    com.epdemic.srm.sms.client.CoreUserInfoClient: DEBUG
